name: Deploy to Production

on:
  push:
    branches:
      - main
    paths:
      - 'backend_strapi/**'


jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # 1. Клонируем репозиторий
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Устанавливаем Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'v22.12.0' # Используйте подходящую версию Node.js для вашего приложения

    # 3. Установка зависимостей для frontend
    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend # Указываем путь к папке frontend, где находится package.json

    # 4. Сборка фронтенда
    - name: Build frontend
      run: npm run build
      working-directory: ./frontend 
      
    - name: Check for backend changes
      id: backend_changes
      run: |
        # Проверяем изменения в папке backend_strapi
        if git diff --quiet HEAD~1 HEAD -- backend_strapi; then
          echo "no_changes=true" >> $GITHUB_ENV
        else
          echo "no_changes=false" >> $GITHUB_ENV
        fi

    # 5. Установка зависимостей и сборка backend (только если были изменения)
    - name: Install backend dependencies and build
      if: env.no_changes == 'false'
      run: |
        npm install
        npm run build
      working-directory: ./backend_strapi
      
    # 6. Деплой на сервер
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd frontend 
          git pull origin main
          npm ci
          npm run build
          pm2 restart 6 

          cd backend_strapi
          git pull origin main
          npm ci
          npm run build 
          pm2 restart 5 
